In [1]:
import numpy as np
import pandas as pd


In [2]:
np.__version__

'2.1.3'

In [3]:
list=[1,2,3,4,5,6,7,8,9,10]
type(list)


list

In [5]:
arr=np.array(list)
type(arr)

numpy.ndarray

In [7]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
np.arange(20,50,5)   #print 20 to 50 by step 5 \\ start-end-step

array([20, 25, 30, 35, 40, 45])

In [9]:
np.arange(20,10)

array([], dtype=int64)

In [10]:
np.arange(-20,10)    #the frist element is always biggest

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [11]:
np.zeros(2)

array([0., 0.])

In [12]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [13]:
np.zeros((2,4),dtype = int)     #this is two-d-array , 2 is for row and 4 is columns

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
np.ones((9,9),dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [15]:
np.arange(1,13).reshape(3,4)    #converted 3 rows and 4 column

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
np.random.random((1,5))          #genrate random no. 1 to 5

array([[0.79779147, 0.00231592, 0.16350919, 0.22520543, 0.93293937]])

In [17]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [18]:
np.random.rand(2,6)           #bu default gives float values

array([[0.22774026, 0.91477562, 0.93614977, 0.85600015, 0.36000823,
        0.34808777],
       [0.39188444, 0.2287628 , 0.50242509, 0.14054095, 0.45668984,
        0.40780095]])

In [19]:
np.random.randint(2,6,4)             #it gives integer values 2 to 6 ,4 is size

array([5, 3, 5, 3], dtype=int32)

In [20]:
np.random.randint(10,50 ,(10,5))    #10*5 matrix

array([[47, 15, 45, 45, 28],
       [34, 45, 12, 39, 24],
       [48, 29, 33, 45, 26],
       [40, 45, 20, 21, 12],
       [40, 18, 17, 47, 31],
       [14, 28, 14, 38, 33],
       [12, 24, 41, 49, 49],
       [17, 23, 31, 43, 49],
       [46, 38, 21, 15, 42],
       [43, 49, 25, 36, 44]], dtype=int32)

In [21]:
# reshape the lsit
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
b = np.random.randint(10,20,(5,4))
b

array([[11, 19, 13, 12],
       [11, 12, 10, 19],
       [16, 13, 12, 11],
       [16, 16, 16, 10],
       [10, 15, 10, 16]], dtype=int32)

In [23]:
b[1:3]

array([[11, 12, 10, 19],
       [16, 13, 12, 11]], dtype=int32)

In [24]:
b[1:4]

array([[11, 12, 10, 19],
       [16, 13, 12, 11],
       [16, 16, 16, 10]], dtype=int32)

In [25]:
b[1,-1]

np.int32(19)

In [26]:
b[2,3]       #the 2 is row and 3 is column

np.int32(11)

In [27]:
b[-5,-3]    #commma(,) is used for get element

np.int32(19)

In [28]:
b[2:4]

array([[16, 13, 12, 11],
       [16, 16, 16, 10]], dtype=int32)

In [29]:
b[-4:4]

array([[11, 12, 10, 19],
       [16, 13, 12, 11],
       [16, 16, 16, 10]], dtype=int32)

In [30]:
b[-5:3]    

array([[11, 19, 13, 12],
       [11, 12, 10, 19],
       [16, 13, 12, 11]], dtype=int32)

In [31]:
arr = np.random.randint(0,100,(10,10))
arr

array([[96, 44, 17, 16, 40, 25, 33, 21,  1, 98],
       [ 0, 56, 26,  6, 11, 61, 60, 91,  0, 27],
       [87, 55, 71, 25, 52, 26, 29, 66, 79, 66],
       [44, 92, 87, 81, 66, 37, 82, 72, 49, 44],
       [62, 41, 13, 74, 15, 75, 63, 57, 68, 16],
       [76, 75, 55, 90, 36,  4, 83, 16, 67, 30],
       [90, 14, 54, 45, 71, 28, 40, 92, 92, 62],
       [59, 54, 60, 73, 18, 26, 34, 12, 72, 46],
       [46, 15, 87, 41,  2, 31, 29, 17, 63, 50],
       [83, 74, 68, 70, 28, 53,  9, 41, 56, 98]], dtype=int32)

In [32]:
arr[-5:-1]    

array([[76, 75, 55, 90, 36,  4, 83, 16, 67, 30],
       [90, 14, 54, 45, 71, 28, 40, 92, 92, 62],
       [59, 54, 60, 73, 18, 26, 34, 12, 72, 46],
       [46, 15, 87, 41,  2, 31, 29, 17, 63, 50]], dtype=int32)

In [33]:
arr[5,5]

np.int32(4)

In [34]:
arr[4,3]

np.int32(74)

In [35]:
arr[-2,-2]

np.int32(63)

In [36]:
arr[::2]

array([[96, 44, 17, 16, 40, 25, 33, 21,  1, 98],
       [87, 55, 71, 25, 52, 26, 29, 66, 79, 66],
       [62, 41, 13, 74, 15, 75, 63, 57, 68, 16],
       [90, 14, 54, 45, 71, 28, 40, 92, 92, 62],
       [46, 15, 87, 41,  2, 31, 29, 17, 63, 50]], dtype=int32)

In [37]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [38]:
max(a)

np.int64(5)

In [39]:
a.mean()

np.float64(2.5)

In [40]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [41]:
a.reshape(2,3)           #2*3=6

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
mat = np.random.randint(0,100,(10,10))
mat

array([[11, 76, 92, 41, 53, 23, 94, 71, 67, 85],
       [ 2, 73, 19, 35, 14, 96, 54,  0, 63, 10],
       [56, 46, 38,  4, 63,  9, 97, 79, 98, 71],
       [63, 92, 22, 50, 32, 44, 47, 63, 86, 34],
       [20, 98, 54, 76, 19, 80, 10, 82, 83, 75],
       [79, 76,  6, 88, 56, 47, 71, 41, 11, 56],
       [86, 95, 13, 66, 82, 18, 15, 94, 99, 38],
       [78, 73, 98, 22, 47, 51, 43, 80, 41, 79],
       [87, 72, 79, 92, 83, 49, 69, 42, 71, 64],
       [17, 73, 95, 99, 25,  4, 47, 83, 31,  0]], dtype=int32)

In [43]:
row = 4
col = 5

In [44]:
mat[row,col]

np.int32(80)

In [45]:
mat[7]

array([78, 73, 98, 22, 47, 51, 43, 80, 41, 79], dtype=int32)

In [46]:
mat[7,4]

np.int32(47)

In [47]:
mat[2:4,2:4]                #row 2 to 4 and column 2 to 4

array([[38,  4],
       [22, 50]], dtype=int32)

In [48]:
 mat[3:5,3:5]

array([[50, 32],
       [76, 19]], dtype=int32)

In [49]:
mat[:8]

array([[11, 76, 92, 41, 53, 23, 94, 71, 67, 85],
       [ 2, 73, 19, 35, 14, 96, 54,  0, 63, 10],
       [56, 46, 38,  4, 63,  9, 97, 79, 98, 71],
       [63, 92, 22, 50, 32, 44, 47, 63, 86, 34],
       [20, 98, 54, 76, 19, 80, 10, 82, 83, 75],
       [79, 76,  6, 88, 56, 47, 71, 41, 11, 56],
       [86, 95, 13, 66, 82, 18, 15, 94, 99, 38],
       [78, 73, 98, 22, 47, 51, 43, 80, 41, 79]], dtype=int32)

In [50]:
mat[:,8]        #print 8 no. column

array([67, 63, 98, 86, 83, 11, 99, 41, 71, 31], dtype=int32)

In [51]:
mat[3:-3]         

array([[63, 92, 22, 50, 32, 44, 47, 63, 86, 34],
       [20, 98, 54, 76, 19, 80, 10, 82, 83, 75],
       [79, 76,  6, 88, 56, 47, 71, 41, 11, 56],
       [86, 95, 13, 66, 82, 18, 15, 94, 99, 38]], dtype=int32)

In [52]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a = np.random.randint(1,100,(10,10))
a

array([[24, 64, 80,  8, 90, 56, 52, 99, 37,  5],
       [51, 10, 78, 88, 37, 76, 91, 60, 83, 94],
       [60, 58,  6, 83, 83, 43, 13, 42, 53, 72],
       [43, 11, 33, 40, 78, 81, 94, 34, 35, 21],
       [72, 91, 11, 42,  8, 50, 28, 64, 44, 79],
       [99, 32, 56, 15, 15, 20, 14, 52, 36, 17],
       [34, 24, 58, 86, 88, 58, 48, 67,  3, 67],
       [44, 17, 89,  2, 10, 19, 87, 27,  8, 76],
       [45, 23,  5, 17, 12, 19, 89, 41, 59, 11],
       [90, 15, 65, 33, 68, 28, 89, 26, 43, 26]], dtype=int32)

In [54]:
a[0:5]

array([[24, 64, 80,  8, 90, 56, 52, 99, 37,  5],
       [51, 10, 78, 88, 37, 76, 91, 60, 83, 94],
       [60, 58,  6, 83, 83, 43, 13, 42, 53, 72],
       [43, 11, 33, 40, 78, 81, 94, 34, 35, 21],
       [72, 91, 11, 42,  8, 50, 28, 64, 44, 79]], dtype=int32)

In [55]:
a[2,2]

np.int32(6)

In [56]:
a[3]

array([43, 11, 33, 40, 78, 81, 94, 34, 35, 21], dtype=int32)

In [57]:
a[4,0]

np.int32(72)

In [58]:
a[-9,-2]

np.int32(83)

In [59]:
b = np.arange(1,10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
b.min()

np.int64(1)