In [1]:
import numpy as np

In [2]:
#create an array from a list
a=np.array([1,2,3])
print("array a:",a)

array a: [1 2 3]


In [3]:
#create an array with evenly spaced values
b=np.arange(0,10,2)
print("array b:",b)

array b: [0 2 4 6 8]


In [4]:
b1=np.arange(0,10,3)
print("array b1:",b1)

array b1: [0 3 6 9]


In [5]:
#create an array filled with zeros
c=np.zeros((2,3))
print("array c:",c)

array c: [[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
c=np.zeros((2,3),dtype=int)
print("array c:",c)

array c: [[0 0 0]
 [0 0 0]]


In [7]:
#create an array filled with ones
d=np.ones((3,2))
print("array d:",d)

array d: [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
d=np.ones((3,2),dtype=int)
print("array d:",d)

array d: [[1 1]
 [1 1]
 [1 1]]


In [9]:
#create an identity matrix
e=np.eye(4)
print("indentity matrix:",e)

indentity matrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
i=np.eye(10)
print("Identity matrix:",i)

Identity matrix: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [11]:
#reshape an array
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(1,3)) # reshape to 1x3
print("Reshaped array:",reshaped)

Reshaped array: [[1 2 3]]


In [12]:
#reshape an array
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(3,1)) # reshape to 1x3
print("Reshaped array:",reshaped)

Reshaped array: [[1]
 [2]
 [3]]


In [13]:
#flatten an array
f1=np.array([[1,2],[3,4]])
flatten=f1.flatten()
print("flattened array:",flatten)

flattened array: [1 2 3 4]


In [14]:
#flatten an array
f1=np.array([[1,2],[3,4]])
ravel=f1.ravel()
print("flattened array:",ravel)

flattened array: [1 2 3 4]


In [15]:
#flatten an array
f1=np.array([[1,2],[3,4],[5,6],[7,8]])
ravel=np.ravel(f1)
print("flattened array:",ravel)

flattened array: [1 2 3 4 5 6 7 8]


In [16]:
#transpose an array
e1=np.array([[1,2],[3,4]])
transposed=np.transpose(e1)
print("transposed array:",transposed)

transposed array: [[1 3]
 [2 4]]


In [17]:
#stack arrays vertically 
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.vstack([a2,b2]) #stack a2 and b2 vertically
print("stacked array:",stacked)

stacked array: [[1 2]
 [3 4]]


In [18]:
#stack arrays horizontally 
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.hstack([a2,b2]) #stack a2 and b2 horizontally
print("stacked array:",stacked)

stacked array: [1 2 3 4]


In [19]:
import numpy as np
a=np.random.randint(0,100,(10,10))
a

array([[53, 34, 16, 75, 89, 31, 91, 20, 59,  9],
       [32, 85, 98, 26, 94, 82, 30, 30, 36, 61],
       [51, 16,  3,  5, 93, 13, 36,  4, 23, 99],
       [43,  0, 85, 46, 95, 40, 17,  1, 45, 98],
       [85,  7, 11, 37, 89, 39, 77, 20, 34, 45],
       [67, 93, 99, 39, 79, 15, 54, 68, 74, 43],
       [83, 94, 92,  4, 11, 55, 77, 53, 92, 52],
       [71,  9, 98, 10, 89, 29, 84, 55, 44, 35],
       [55, 73, 89, 52, 46, 36, 79, 28,  3,  9],
       [ 0, 11, 53,  6, 99, 99, 82, 96, 35, 75]], dtype=int32)

In [20]:
a[::-1]

array([[ 0, 11, 53,  6, 99, 99, 82, 96, 35, 75],
       [55, 73, 89, 52, 46, 36, 79, 28,  3,  9],
       [71,  9, 98, 10, 89, 29, 84, 55, 44, 35],
       [83, 94, 92,  4, 11, 55, 77, 53, 92, 52],
       [67, 93, 99, 39, 79, 15, 54, 68, 74, 43],
       [85,  7, 11, 37, 89, 39, 77, 20, 34, 45],
       [43,  0, 85, 46, 95, 40, 17,  1, 45, 98],
       [51, 16,  3,  5, 93, 13, 36,  4, 23, 99],
       [32, 85, 98, 26, 94, 82, 30, 30, 36, 61],
       [53, 34, 16, 75, 89, 31, 91, 20, 59,  9]], dtype=int32)

In [21]:
a[::-2]

array([[ 0, 11, 53,  6, 99, 99, 82, 96, 35, 75],
       [71,  9, 98, 10, 89, 29, 84, 55, 44, 35],
       [67, 93, 99, 39, 79, 15, 54, 68, 74, 43],
       [43,  0, 85, 46, 95, 40, 17,  1, 45, 98],
       [32, 85, 98, 26, 94, 82, 30, 30, 36, 61]], dtype=int32)

In [22]:
a[::-3]

array([[ 0, 11, 53,  6, 99, 99, 82, 96, 35, 75],
       [83, 94, 92,  4, 11, 55, 77, 53, 92, 52],
       [43,  0, 85, 46, 95, 40, 17,  1, 45, 98],
       [53, 34, 16, 75, 89, 31, 91, 20, 59,  9]], dtype=int32)

In [23]:
row=4
col=5

In [24]:
col

5

In [25]:
row

4

In [26]:
a

array([[53, 34, 16, 75, 89, 31, 91, 20, 59,  9],
       [32, 85, 98, 26, 94, 82, 30, 30, 36, 61],
       [51, 16,  3,  5, 93, 13, 36,  4, 23, 99],
       [43,  0, 85, 46, 95, 40, 17,  1, 45, 98],
       [85,  7, 11, 37, 89, 39, 77, 20, 34, 45],
       [67, 93, 99, 39, 79, 15, 54, 68, 74, 43],
       [83, 94, 92,  4, 11, 55, 77, 53, 92, 52],
       [71,  9, 98, 10, 89, 29, 84, 55, 44, 35],
       [55, 73, 89, 52, 46, 36, 79, 28,  3,  9],
       [ 0, 11, 53,  6, 99, 99, 82, 96, 35, 75]], dtype=int32)

In [27]:
a[row,col]

np.int32(39)

In [28]:
col=6

In [29]:
a[row,col]

np.int32(77)

In [30]:
a[:,col]

array([91, 30, 36, 17, 77, 54, 77, 84, 79, 82], dtype=int32)

In [31]:
a[:,-3]

array([20, 30,  4,  1, 20, 68, 53, 55, 28, 96], dtype=int32)

In [32]:
a[:,8]

array([59, 36, 23, 45, 34, 74, 92, 44,  3, 35], dtype=int32)

In [33]:
a[5:7]

array([[67, 93, 99, 39, 79, 15, 54, 68, 74, 43],
       [83, 94, 92,  4, 11, 55, 77, 53, 92, 52]], dtype=int32)

In [34]:
a[0:10]

array([[53, 34, 16, 75, 89, 31, 91, 20, 59,  9],
       [32, 85, 98, 26, 94, 82, 30, 30, 36, 61],
       [51, 16,  3,  5, 93, 13, 36,  4, 23, 99],
       [43,  0, 85, 46, 95, 40, 17,  1, 45, 98],
       [85,  7, 11, 37, 89, 39, 77, 20, 34, 45],
       [67, 93, 99, 39, 79, 15, 54, 68, 74, 43],
       [83, 94, 92,  4, 11, 55, 77, 53, 92, 52],
       [71,  9, 98, 10, 89, 29, 84, 55, 44, 35],
       [55, 73, 89, 52, 46, 36, 79, 28,  3,  9],
       [ 0, 11, 53,  6, 99, 99, 82, 96, 35, 75]], dtype=int32)

In [35]:
a[2:6,2:4]

array([[ 3,  5],
       [85, 46],
       [11, 37],
       [99, 39]], dtype=int32)

In [36]:
a[1:2,2:4]

array([[98, 26]], dtype=int32)

In [37]:
a[2:3,2:3]

array([[3]], dtype=int32)

In [38]:
a[2:4,3:5]

array([[ 5, 93],
       [46, 95]], dtype=int32)

In [39]:
b=np.arange(27).reshape(3,3,3) 
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [40]:
b[2]


array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [41]:
b[:]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [42]:
b[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [43]:
b[::-1]

array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]]])

In [44]:
b[::-2]

array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]]])

In [45]:
b[:]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [46]:
b[0,1]

array([3, 4, 5])

In [47]:
b[1,2]

array([15, 16, 17])

In [48]:
b[2,2]

array([24, 25, 26])

In [49]:
b[0,1,:]

array([3, 4, 5])

In [50]:
b[1,1,:]

array([12, 13, 14])

In [51]:
b[1,2,0]

np.int64(15)

In [52]:
b[0,:,1]

array([1, 4, 7])

In [53]:
b[:]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [55]:
b[:,2,1]

array([ 7, 16, 25])

In [56]:
b[1,:,1]

array([10, 13, 16])

In [57]:
b[0::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [58]:
mat=np.arange(0,100)
mat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [59]:
mat>50

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [60]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [61]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [62]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [63]:
mat[mat==50]

array([50])

In [64]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [65]:
mat>0

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [66]:
mat[mat>0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [67]:
mat>=0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [68]:
mat<0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [69]:
mat<=0

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [70]:
mat[mat<=0]

array([0])

In [71]:
mat[mat>=0]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [72]:
mat[mat==20]

array([20])

#numpy operations

In [73]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [74]:
arr2=np.ones(5,dtype=int)
arr2

array([1, 1, 1, 1, 1])

In [75]:
arr1+arr2

array([2, 3, 4, 5, 6])

In [76]:
arr1-arr2

array([0, 1, 2, 3, 4])

In [77]:
arr1*arr2

array([1, 2, 3, 4, 5])

In [78]:
arr1/arr2

array([1., 2., 3., 4., 5.])

In [79]:
arr1//arr2

array([1, 2, 3, 4, 5])

In [80]:
arr1%arr2

array([0, 0, 0, 0, 0])

In [81]:
arr1**arr2

array([1, 2, 3, 4, 5])

In [82]:
arr1**arr1


array([   1,    4,   27,  256, 3125])

In [83]:
#sum of the numbers
arr1.sum()

np.int64(15)

In [84]:
#max of numbers
arr1.max()

np.int64(5)

In [85]:
#min of numbers
arr1.min()

np.int64(1)

In [86]:
#mean 
arr1.mean()

np.float64(3.0)

In [88]:
from numpy import*
#median
median(arr1)

np.float64(3.0)

In [89]:
#standard deviation
arr1.std()

np.float64(1.4142135623730951)

In [90]:
#variance
arr1.var()

np.float64(2.0)

In [91]:
#sin fuction
np.sin(arr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [92]:
#cos fuction
np.cos(arr1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [93]:
#tan fuction
np.tan(arr1)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [94]:
#creating 2 arrays
a1=np.array([[1,2,3],[4,5,6]])
print(a1)
b1=np.array([[7,8,9],[5,6,7]])
print(b1)

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [5 6 7]]


In [95]:
vertical_stack=np.vstack((a1,b1))
print(vertical_stack)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [5 6 7]]


In [96]:
#horizontally stacked
horizontal_stack=np.hstack((a1,b1))
print(horizontal_stack)

[[1 2 3 7 8 9]
 [4 5 6 5 6 7]]


In [97]:
print(a1)

[[1 2 3]
 [4 5 6]]


In [98]:
splitting=np.split(a1,2)
print(splitting)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [99]:
splitting=np.vsplit(a1,2)
print(splitting)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [100]:
splitting=np.hsplit(a1,3)
print(splitting)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [101]:
arr=np.array([[5,4,4,7],[7,5,0,6],[4,3,7,6]])
print(arr)

[[5 4 4 7]
 [7 5 0 6]
 [4 3 7 6]]


In [102]:
#vertical splitting
splitting=np.vsplit(arr,3)
print(splitting)

[array([[5, 4, 4, 7]]), array([[7, 5, 0, 6]]), array([[4, 3, 7, 6]])]


In [103]:
#horizontal splitting
splitting=np.hsplit(arr,4)
print(splitting)

[array([[5],
       [7],
       [4]]), array([[4],
       [5],
       [3]]), array([[4],
       [0],
       [7]]), array([[7],
       [6],
       [6]])]


In [104]:
#view and copy fuctions
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [105]:
b=a[0,:]
print(b)

[1 2 3 4]


In [106]:
b[0]=90
print(b)

[90  2  3  4]


In [107]:
print(a)

[[90  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [108]:
b1=a.copy()
print(b1)

[[90  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [109]:
b[1]=100
print(b)

[ 90 100   3   4]


In [110]:
print(b1)

[[90  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [111]:
print(a)

[[ 90 100   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [112]:
u=np.array([1,2,3,4,2,4,5,6,7,8,4,9,10,11,10,11,8,9,11,2,1,12,12,13])
print(u)

[ 1  2  3  4  2  4  5  6  7  8  4  9 10 11 10 11  8  9 11  2  1 12 12 13]


In [113]:
unique_items=np.unique(u)
print(unique_items)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]


In [114]:
#to get indexes of unique values
index_values=np.unique(u,return_index=True)
print(index_values)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]), array([ 0,  1,  2,  3,  6,  7,  8,  9, 11, 12, 13, 21, 23]))


In [115]:
#frequency count of unique values
occurance_count=np.unique(u,return_counts=True)
print(occurance_count)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]), array([2, 3, 1, 3, 1, 1, 1, 2, 2, 2, 3, 2, 1]))


In [117]:
u2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[1,2,3,4]])
print(u2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


In [119]:
uniq=np.unique(u2d)
uniq

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [120]:
uniq2=np.unique(u2d,return_index=True,return_counts=True)
uniq2

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1]))

In [121]:
#1D array
f1=np.array([1,2,3,4,5,6])
flip1=np.flip(f1)
print(flip1)

[6 5 4 3 2 1]


In [122]:
#2D array
f2=np.array([[1,2,3],[3,4,5],[5,6,7]])
flip2=np.flip(f2)
print(flip2)

[[7 6 5]
 [5 4 3]
 [3 2 1]]


In [124]:
flip3=np.flip(f2,axis=0)
print(flip3)

[[5 6 7]
 [3 4 5]
 [1 2 3]]


In [125]:
#reverse only columns
flip4=np.flip(f2,axis=1)
print(flip4)

[[3 2 1]
 [5 4 3]
 [7 6 5]]


In [126]:
#reversing single row at index position
flip5=f2[0]=np.flip(f2[0])
print(flip5)

[1 2 3]


In [127]:
flip6=f2[2]=np.flip(f2[2])
print(flip6)

[5 6 7]


In [128]:
#reversing single column at index position
flip7=f2[:,1]=np.flip(f2[:,1])
print(flip7)

[2 4 6]
